# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Jon Snow's Webpage
email: joaojdneves@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Jo達o Neves, an accomplished professional, boasts a comprehensive background in the realms of machine learning, software engineering, and data science.
  As a Senior Machine Learning Engineer at FARFETCH, Jo達o has been integral in crafting a virtual assistant powered by Large Language Models (LLMs) and optimizing recommendation systems using a Vector Search Engine.
  His tenure as a Technical Lead Engineer at Siemens saw him designing and implementing cybersecurity systems, including proprietary MLOps frameworks and automated platforms.
  Jo達o's expertise extends to cloud-based machine learning, evidenced by his role as a Cloud Machine Learning Engineer at Siemens, focusing on malware detection engine development.
  With an educational foundation in Mathematical Statistics and Probability, as well as Computational and Applied Mathematics, Jo達o's journey underscores a wealth of skills across diverse technologies and methodologies.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jonsnowseven.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 7_snow_storm
github_username:  jonsnowseven

# Build settings
remote_theme: hacker
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
